Generate a variable dictionary and values
lfc-256/ControlBDA pull request #18
Opened 2020-05-22 05:08 UTC by lfc-256

This dictionary include all parameters that we need to use in Matlab and Scilab.

Resolves-Issue #9

2020-05-25 20:08 UTC, jcontrolresearch requested changes
Please include a header to provide information about dictionary, for instance:

![image](https://user-images.githubusercontent.com/57429237/82840784-659a0900-9e99-11ea-907c-4d7092ab5a30.png)

split parameters on control parameters/ vehicle parameters/ trailer parameters as comments and variables in each section

2020-05-26 18:14 UTC, lfc-256 commented
The changes to provide better organization of information and remove scripts for Scilab have been made.

2020-05-26 18:35 UTC, raul-rd approved these changes

2020-05-26 18:48 UTC, SaraML approved these changes

2020-05-26 19:15 UTC, lfc-256 commented
Hi Julio, I made the changes  and this generate conflicts with the merge pull request. What can I do? Thanks!!!

2020-05-26 19:59 UTC, jcontrolresearch requested changes
Use %% to header comment in order to define scrip information to future script external calls

2020-05-26 20:02 UTC, JControlReserch commented
> Hi Julio, I made the changes and this generate conflicts with the merge pull request. What can I do? Thanks!!!

@lfc-256 please click on highlighted section to see solution

![image](https://user-images.githubusercontent.com/57429237/82944953-baa15200-9f61-11ea-99e5-aba8e66a0ca5.png)

2020-05-26 20:06 UTC, jcontrolresearch requested changes
Team @HugoLeyvaOax , @SaraML , @raul-rd  please take a look in [code section for matlab scritps](https://www.mathworks.com/help/matlab/matlab_prog/run-sections-of-programs.html) for further develop scripts

2020-05-26 20:06 UTC, JControlReserch commented on Scripts/variable_dictionary.m
> +%{
Here must be %%

2020-05-26 20:06 UTC, JControlReserch commented on Scripts/variable_dictionary.m
> +%}
Here to... %% please see [Code section spec Matlab](https://www.mathworks.com/help/matlab/matlab_prog/run-sections-of-programs.html)

2020-05-26 20:22 UTC, HugoLeyvaOax commented
Very Well

2020-05-26 20:47 UTC, raul-rd approved these changes

2020-05-26 20:49 UTC, raul-rd approved these changes

2020-05-26 21:01 UTC, lfc-256 commented
Thanks! I made the changes and follow the next steps [https://github.com/githubteacher/github-for-developers-sept-2015/issues/648#issuecomment-144488223](solution url) and ti worked.

2020-05-26 21:08 UTC, raul-rd approved these changes

2020-05-26 21:10 UTC, SaraML approved these changes

2020-05-27 00:07 UTC, jcontrolresearch requested changes
Follow this structure :)

[here](https://github.com/lfc-256/ControlBDA/pull/18#pullrequestreview-417862759)

2020-05-27 00:07 UTC, JControlReserch commented on Scripts/variable_dictionary.m
> +
you forgot close the header with %% :)

2020-05-27 16:18 UTC, jcontrolresearch approved these changes
Great !

2020-05-27 16:33 UTC, SaraML approved these changes

2020-05-27 16:47 UTC, raul-rd approved these changes

2020-05-27 17:04 UTC, merged