Variables of vehicle and trailer added
lfc-256/ControlBDA pull request #22
Opened 2020-06-05 10:59 UTC by lfc-256

Some variables used in de dynamics model of the vehicle and trailer added.

2020-06-05 14:20 UTC, HugoLeyvaOax commented
Very well.

2020-06-05 14:20 UTC, HugoLeyvaOax approved these changes

2020-06-05 21:44 UTC, JControlReserch commented on Scripts/variable_dictionary.m
> +% No. Manuever
%% Maneuver number 

Use %% to split code in sections. This in order to document easily in the future

2020-06-05 21:45 UTC, JControlReserch commented on Scripts/variable_dictionary.m
> +%Vehicle parameters 2
Why is call Vehicle parameter 2?

2020-06-05 21:46 UTC, jcontrolresearch requested changes
Please review comments and commit fixes

2020-06-05 22:19 UTC, JControlReserch commented
@JControlReserch please update types of trailer ASAP

2020-06-07 00:25 UTC, JControlReserch commented
I take a look into trailers types but actually is assigned to you guys @lfc-256, @raul-rd, @SaraML on issue #13. Please take a look.

Anyway I found this table which is pretty useful at start point 
![image](https://user-images.githubusercontent.com/57429237/83957154-266d9f80-a82b-11ea-91f8-9be8e6fe1925.png)

Please use as starting point.
Consider to automate master script to analyse the control algorithm in another point of view. We will discusses this on next stand up

2020-06-16 05:31 UTC, jcontrolresearch approved these changes
We follow matrix issue on assigned pull request, now I merge dict file to master

2020-06-16 05:31 UTC, merged